import "../styles/globals.css";
import "../styles/dashboard.css";
import useScript from "../hooks/useScript";
import Loader from "../components/Loader";
import { useState } from "react";
import { SessionProvider } from "next-auth/react";
import Head from "next/head";

function MyApp({ Component, pageProps: { session, ...pageProps } }) {
  useScript(
    "https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
  );

  let userObj = {
    // userName: "",
    // email: "",
    mobileNumber: "",
    education: "",
    skills: "",
    companyName: "",
    collegeName: "",
    designation: "",
    experience: "",
    linkedIn: "",
    fileName: "form",
    role: "",
  };

  const [isLoading, setIsLoading] = useState(false);
  const [data, setData] = useState(userObj);

  return (
    <SessionProvider session={session}>
      {isLoading && <Loader />}
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component
        {...pageProps}
        isLoading={isLoading}
        setIsLoading={setIsLoading}
        data={data}
        setData={setData}
      />
    </SessionProvider>
  );
}

export default MyApp;
