import "../styles/globals.css";
import Loader from "../components/Loader";
import { useState } from "react";
import { SessionProvider } from "next-auth/react";
import Head from "next/head";

function MyApp({ Component, pageProps: { session, ...pageProps } }) {
  let userObj = {
    userName: "",
    email: "",
    mobileNumber: "",
    education: "",
    skills: "",
    companyName: "",
    collegeName: "",
    designation: "",
    experience: "",
    linkedIn: "",
    fileName: "form",
    role: "",
    scores:{},
    matchedSkills:[],
    skillsRequired:[],
  };

  const [isLoading, setIsLoading] = useState(false);
  const [data, setData] = useState(userObj);

  return (
    <SessionProvider session={session}>
      {isLoading && <Loader />}
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component
        {...pageProps}
        
      />
    </SessionProvider>
  );
}

export default MyApp;
