import Head from 'next/head'
import SkillsMatched from '../components/SkillsMatched'
const dashboard = () => {
  const skills = ['mongodb', 'nodejs']
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='p-5'>
        <SkillsMatched role='mern' skills={skills} />
      </main>
    </>
  )
}

export default dashboard
