import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { useState } from "react";

export default function Home() {

  const [file, setFile] = useState();

  function fileHandler(e) {
    console.log(e.target.files);
    setFile(e.target.files[0]);
  }

  return (
    <>
      <Head>
        <title>Resume Parser | HomePage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container-fluid py-5">
          <div>
            <form className="col-5 mx-auto">
              <h6>Upload Resumes</h6>
              <input
                type="file"
                name="resume"
                multiple
                required
                className="d-block py-3"
                onChange={fileHandler}
              ></input>
              <button type="button" className="btn btn-outline-success">
                Upload
              </button>
            </form>
          </div>
          <div className="text-center py-3">
            ------------------------------OR----------------------------
          </div>
          <div className="text-center">
            <Link href={"/resumeForm"}>
              <button type="button" className="btn btn-outline-primary">
                Enter Details Manually
              </button>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}
