import Head from "next/head";

function form() {
    return (
        <>
            <Head>
                <title>Resume Parser | Manual Form</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="container py-5">
                <input type="button" value="button" />
            </main>
        </>
    );
}

export default form;