import Head from "next/head";
import { useState } from "react";
import Router, { useRouter } from 'next/router'
import Loader from "../components/Loader";


function resumeForm(props) {
    let tempObj = {
        userName: "",
        email: "",
        mobileNumber: "",
        education: "",
        skills: "",
        companyName: "",
        collegeName: "",
        designation: "",
        experience: "",
        linkedIn: "",
        fileName: "form",
        role: "",
      };

    const [user, setUser] = useState(props.data);
    const router = useRouter();
    function changeHandler(e) {
        setUser({
            ...user,
            [e.target.name]: e.target.value
        });
    }

    async function submitHandler(e) {
        props.setIsLoading(true);
        e.preventDefault();
        const response = await fetch("/api/formUpload", {
            method: "POST",
            body: JSON.stringify(user),
            headers: {
                "Content-Type": "application/json",
            },
        });

        const res = await response.json();
        props.setIsLoading(false);
        res.success == true ? alert(res.message) : alert(res.error);
        //to clear the form
        props.setData(tempObj);
        router.push("/");
    }

    return (
        <>
            <Head>
                <title>Manual Form</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="container-fluid py-5">
                <form className="col-5 mx-auto" onSubmit={submitHandler} method={"POST"} encType="multipart/form-data">
                    {props.isLoading && <Loader />}
                    <h6>Enter Details:</h6>

                    <div className="d-flex flex-column">

                        <label htmlFor="role">Enter the job role you are aspiring for* :</label>
                        <select required name="role" id="role" className="my-2" value={user.role === null ? " " : user.role} onChange={changeHandler}>
                            <option value="" disabled selected>Select from the options!</option>
                            <option value="mern developer">MERN Stack Developer</option>
                            <option value="java developer">JAVA Developer</option>
                        </select>

                        <label htmlFor="userName">Full Name* :</label>
                        <input required type="text" name="userName"
                            id="name" placeholder="Enter Your Full name" className="my-2" value={user.userName === null ? " " : user.userName} onChange={changeHandler} />

                        <label htmlFor="email">Email* :</label>
                        <input required type="email" name="email"
                            id="name" placeholder="Enter Your Valid Email" className="my-2" value={user.email === null ? " " : user.email} onChange={changeHandler} />


                        <label htmlFor="email">Mobile Number:</label>
                        <input type="tel" name="mobileNumber"
                            id="name" placeholder="Enter Your Mobile Number" className="my-2" value={user.mobileNumber === null ? " " : user.mobileNumber} onChange={changeHandler} />


                        <label htmlFor="email">Education:</label>
                        <input type="text" name="education"
                            id="name" placeholder="Enter your Highest Education" className="my-2" value={user.education === null ? " " : user.education} onChange={changeHandler} />


                        <label htmlFor="email">Skills* :</label>
                        <input required type="text" name="skills"
                            id="name" placeholder="Enter your skills separated with comma" className="my-2" value={user.skills === null ? " " : user.skills} onChange={changeHandler} />


                        <label htmlFor="email">Company Name:</label>
                        <input type="text" name="companyName"
                            id="name" placeholder="Enter your current Company Name" className="my-2" value={user.companyName === null ? " " : user.companyName} onChange={changeHandler} />


                        <label htmlFor="email">College Name:</label>
                        <input type="text" name="collegeName"
                            id="name" placeholder="Enter your College Name" className="my-2" value={user.collegeName === null ? " " : user.collegeName} onChange={changeHandler} />


                        <label htmlFor="email">Designation:</label>
                        <input type="text" name="designation"
                            id="name" placeholder="Enter your Designation" className="my-2" value={user.designation === null ? " " : user.designation} onChange={changeHandler} />


                        <label htmlFor="email">Experience:</label>
                        <input type="number" name="experience"
                            id="text" placeholder="Enter your Experience" className="my-2" value={user.experience === null ? " " : user.experience} onChange={changeHandler} />


                        <label htmlFor="email">LinkedIn URL:</label>
                        <input type="url" name="linkedIn"
                            id="name" placeholder="Enter the Valid URL" className="my-2" value={user.linkedIn === null ? " " : user.linkedIn} onChange={changeHandler} />


                    </div>

                    <button type="submit" className="d-block my-4 btn btn-outline-success">
                        Submit
                    </button>
                </form>
            </main>
        </>
    );
}

export default resumeForm;