import Head from 'next/head'
import Link from 'next/link'
import { useState } from 'react'
import $ from 'jquery'
import { useRouter } from 'next/router'
import Loader from '../components/Loader'
import Navbar from '../components/Navbar'
import clientPromise from '../util/mongodb'

import { getServerSession } from 'next-auth/next'
import { authOptions } from '../pages/api/auth/[...nextauth].js'

export default function upload (props) {
  const router = useRouter()
  const [file, setFile] = useState()
  // const [createObjectURL, setCreateObjectURL] = useState(null);

  function fileHandler (e) {
    if (e.target.files && e.target.files[0]) {
      const i = e.target.files[0]
      setFile(i)
      // setCreateObjectURL(URL.createObjectURL(i));
    }
  }

  async function submitHandler (e) {
    props.setIsLoading(true)
    e.preventDefault()
    const formData = new FormData()
    formData.append('file', file)
    const response = await fetch('/api/fileUpload', {
      method: 'POST',
      body: formData
    })
    const res = await response.json()
    props.setIsLoading(false)

    props.setData(res.userData)
    router.push('/resumeForm')
    // res.success == true ? alert(res.message) : alert(res.error);
    // router.reload();
    // e.target.reset();
  }

  return (
    <>
      <Head>
        <title>Resume Parser | Home</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <main>
        <div className='container-fluid py-5'>
          <div>
            <form
              className='col-5 mx-auto'
              onSubmit={submitHandler}
              method='POST'
              encType='multipart/form-data'
              id='resumeForm'
            >
              <h6>Upload Resumes</h6>
              <input
                id='file'
                type='file'
                name='resume'
                multiple
                required
                className='d-block py-3'
                onChange={fileHandler}
              />

              <button type='submit' className='btn btn-outline-success'>
                Upload
              </button>
            </form>
          </div>
          <div className='text-center py-3'>
            ------------------------------OR----------------------------
          </div>
          <div className='text-center'>
            <Link href='/resumeForm'>
              <button type='button' className='btn btn-outline-primary'>
                Enter Details Manually
              </button>
            </Link>
          </div>
        </div>
      </main>
    </>
  )
}

export async function getServerSideProps (context) {
  const session = await getServerSession(context.req, context.res, authOptions)
  const client = await clientPromise
  const db = await client.db('resumeParser')
  const collection = await db.collection('resumes')

  if (!session) {
    return {
      redirect: {
        destination: '/login',
        permanent: true
      }
    }
  }

  const data = await collection
    .find({ email: session.user.email })
    .toArray()
    .then((data) => data)
    .catch((err) => err)

  if (data.length !== 0) {
    // console.log("user not found");
    return {
      redirect: {
        destination: '/',
        permanent: true
      }
    }
  }

  return {
    props: {}
  }
}
