# Generated by Django 4.1.3 on 2022-11-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0012_resume_filename_alter_resume_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='education',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='email',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='total_experience',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='uploaded_on',
        ),
        migrations.AlterField(
            model_name='resume',
            name='fileName',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
